### ISSUE TITLE
Dashboard: How good are we at Social Coding?

### ISSUE THREAD

**Issue by colossus9** [colossus9/github-admin-toolkit#7]
# Dashboard: How good are we at Social Coding?

Vanity metrics are great (like number of users and repos), but we need a way to further understand how the public github.com and a private **GitHub Enterprise** instance is transforming how individuals, teams and enterprises are collaborating on building software.

**Examples of desired metrics:**

- Measuring "building on top of the shoulder of giants" (i.e. Starred repositories / Gists across teams, across business units)
- Measuring "active re-use" (i.e. fork across teams / across business units)
- Measuring "cross contributions" (i.e. Pull requests across business units)
- Measuring "active social developers" (i.e. developers contributing beyond their team/business unit)
- etc...

Then, for each **metric/behavior**, provide **recommendations**. For example:

- _Building on top of the shoulder of giants_
    - How to write a great `README.md`, a `CONTRIBUTING.md`, maintaining a list of "low hanging fruits" type of defects for contributors to get started, etc...
- etc...

GitHub today does not provide a dashboard or data source could help these individuals, teams and enterprises understand, manage and provide recommendations on how good "we" handle social coding. GitHub is a **Social Coding platform** and "we" need to be good at it.

**Comment by IAmHughes** [comment]
I really like this idea!
